[project]
name = "mocho-train"
version = "0.0.0"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.1",
    "tinygrad",
    "tokenizers>=0.22.2",
]

[tool.uv.sources]
tinygrad = { git = "https://github.com/tinygrad/tinygrad.git" }
